services:
  postgres:
    image: postgres
    container_name: jrjavadev1_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      -  ./data/postgres:/var/lib/postgresql

volumes:
  postgres: